const fs = require("node:fs");
const path = require("node:path");

const sourcePath = path.join("src", "index.ts");
const outputDir = "dist";
const outputPath = path.join(outputDir, "index.js");

if (!fs.existsSync(sourcePath)) {
  console.error("Cannot build: src/index.ts is missing");
  process.exit(1);
}

fs.mkdirSync(outputDir, { recursive: true });
const source = fs.readFileSync(sourcePath, "utf8");
const banner = "// generated by lightweight build script\n";
fs.writeFileSync(outputPath, `${banner}${source}`);
console.log(`Build artifact written to ${outputPath}`);
